services:
  insane:
    image: docker.io/angeladmerkel/insane:latest
    restart: unless-stopped
    privileged: true
    ports:
      - "51234:8080"
    volumes:
      - ${INSANE_STATE_PATH:-./data/state}:/data/state
      - ${INSANE_OUTPUT_PATH:-./data/output}:/data/output
    environment:
      PUID: "${PUID:-568}"
      PGID: "${PGID:-568}"
