services:
  insane:
    build:
      context: .
    image: insane:demo
    container_name: insane-demo
    ports:
      - "51234:8080"
    volumes:
      - ./data/state:/data/state
      - ./data/output:/data/output
    environment:
      PUID: "568"
      PGID: "568"
      InSane__Storage__StatePath: /data/state
      InSane__Storage__OutputPath: /data/output
      InSane__Scanner__EnableDemo: "true"
